### ISSUE TITLE
how to change vp-logo on options page?

### ISSUE THREAD

**Issue by agusmu** [vafour/vafpress-framework#11]
is there any simple way to change vp-logo on the options page?

**Comment by ayublin** [comment]
Yes, it is meant to be changed, you can specify the `logo` within the options array template, so that it will looks like this:

```
return array(
    'title' => __('Vafpress Option Panel', 'vp_textdomain'),
    'page' => __('Vafpress Menu', 'vp_textdomain'),
    'logo' => get_template_directory_uri() . '/public/img/my_logo.png',
    'menus' => array(
        ...
    ),
);
```

**Comment by ayublin** [comment]
And we forgot to mention that for non issue questions please use our support forum instead at [http://support.vafpress.com](http://support.vafpress.com/) :) If the question leads to an issue of the framework, then we can forward it here.
