### ISSUE TITLE
Posts dropdown not showing all posts.

### ISSUE THREAD

**Issue by ivandotv** [vafour/vafpress-framework#12]
I'm test driving the latest version of this framework in combination with [vafpress-framework-theme-boilerplate](https://github.com/vafour/vafpress-framework-theme-boilerplate)
And looking at the theme options -> dynamic -> posts dropdown. 
Only 4 posts are being shown. Is that by design or is this a bug?

**Comment by daviedR** [comment]
Ooops, it seems it's a bug. It will be immediately fixed on the next commit :)
Thanks for reporting this issue

**Comment by daviedR** [comment]
This issue has been fixed now
commit: https://github.com/vafour/vafpress-framework/commit/08b2fc8bcec3b26dda0d44f17166fa6f41390eb2
