### ISSUE TITLE
Theme Check Erros

### ISSUE THREAD

**Issue by grafixes** [vafour/vafpress-framework#15]
Hi,

Small issue, when running the Theme Check plugin, I get a couple of errors:
WARNING: Found PHP short tags in file vafpress-framework/includes/markdown/parser.php.

Line 379: | # PHP and ASP-style processor instructions (<? and <%)

WARNING: file_get_contents was found in the file vafpress-framework/data/sources.php possible file operations.

Line 84: $fonts = file_get_contents(dirname(**FILE**) . '/gwf.json');

Line 102: $fonts   = file_get_contents(dirname(**FILE**) . '/gwf.json');

Line 119: $fonts   = file_get_contents(dirname(**FILE**) . '/gwf.json');

Line 171: $subject = file_get_contents(VP_DIR . '/public/css/vendor/font-awesome.min.css');

REQUIRED: vafpress-framework/classes/option.php. Themes should use add_theme_page() for adding admin pages.

Line 120: $hook_suffix = add_menu_page(

REQUIRED: get_links found in the file vafpress-framework/classes/site/googlewebfont.php. Deprecated since version 2.1. Use get_bookmarks() instead.

Line 61: $links = $this->get_links();

Line 83: public function get_links()

Is it possible for these errors to be fixed?

Best Regards,
Max

**Comment by agusmu** [comment]
Max,

If you want to use it for ThemeForest theme, please use Theme Check + ThemeForest Check plugin, 
http://wordpress.org/plugins/themeforest-check/

It will remove most of warning message above except the last one. But, it is also false positive.

**Comment by ayublin** [comment]
Thanks @agusmu !

What agusmu said are all true, please use both plugins, and other errors that still showing are false positive.

We're not sure why using `file_get_contents` or `add_menu_page` isn't allowed, Vafpress Framework can be used not only in theme, but also plugin, so using `add_menu_page` is the best function we think.

**Comment by agusmu** [comment]
for reference, my pull request above will solve your issue. please check it. I hope Vafpress team approve it.

**Comment by ayublin** [comment]
Yup, will fixes most of the issue but not all of them, and FYI a friend of mine used Vafpress Framework and got accepted, the reviewers at themeforest can understand the situation, so don't worry too much :)

**Comment by archivescode** [comment]
you can try this

http://archivescode.blogspot.com/2015/02/mengatasi-line-35-requireoncedatasource.html

**Comment by archivescode** [comment]
to remove Line 120: $hook_suffix = add_menu_page( you can try this 

http://archivescode.blogspot.com/2015/02/mengatasi-line-120-hooksuffix.html
