### ISSUE TITLE
Lost Focus on Repeated Field

### ISSUE THREAD

**Issue by agusmu** [vafour/vafpress-framework#17]
This issue also happens when I test metabox in your demo http://demo.vafpress.com/#/vafpress-framework

For example, I click "Add More Reference" button, It does add new reference field, but it scrolls down to a wrong place. So, it lost focus on current reference field.

It also happens when you click "Add More Column" and "Add More Row" on the Page Builder demo.

Tested with the latest Firefox and Internet Explorer

**Comment by ayublin** [comment]
Hi,

Thanks for the report! we've just fixed the issue but for now haven't updated the demo.
