### ISSUE TITLE
Request: Slide Sorter

### ISSUE THREAD

**Issue by metalenger** [vafour/vafpress-framework#18]
First of all Superb job on this framework, It just needs a little more work and then it would be the best Open Source Options Framework out there.

One of the thing that I feel is missing is the "Slide Sorter", Where you can add new slide and each slide could have its own set of options (image upload, name, link ...) and of course you should be able to sort them.

This is very useful for custom galleries or custom social icons and ... .

an example: http://i.imgur.com/tlOsKOl.jpg

**Comment by ayublin** [comment]
Hi Metalenger,

Thanks for the kind words!

To achieve that kind of control field will require the options framework class to supports grouping and repeating group as in Metabox, we've thought about this before, but the changes will be quite big, and will require the time we currently don't have, but we may will work on it in the future :)

Another option is to build the custom control yourself, by following the explanation on this page:

http://vafpress.com/documentation/vafpress-framework/controls/customfields.html

Thanks!

**Comment by ayublin** [comment]
FYI, we have a dedicated support forum for feature requests and etc, located at: http://support.vafpress.com/ :)

**Comment by metalenger** [comment]
Thank you so much, I wish Vafpress could live up to its potential as it could be an outstanding framework.
