### ISSUE TITLE
FWD slash missing in constant.php

### ISSUE THREAD

**Issue by dameer** [vafour/vafpress-framework#20]
Not sure whether it was made on purpose or not...

line #36, "constant.php":
defined('VP_PUBLIC_URL')  or define('VP_PUBLIC_URL' , VP_URL        . 'public');

... if no forward slash before 'public' vafpress framework loading will end up with a bunch of javascript errors because files not found. So I just have added FWD slash and everything works wonderful again:

defined('VP_PUBLIC_URL')  or define('VP_PUBLIC_URL' , VP_URL        . '/public');

---

I know this is not a place for a feedback but I have to say that you guys made an extraordinary job here. Really appreciate your work and efforts for the most complete WP library in the world. You saved me a ton of time, can't stop saying THANKS!!!

**Comment by agusmu** [comment]
for reference, my pull request above will solve your issue. please check it. I hope Vafpress team approve it.

**Comment by ayublin** [comment]
Sorry about this issue, I made a silly mistake, changed the constant and only tested the framework as a plugin, but should be fixed now :) Thanks!
