### ISSUE TITLE
WP deprecated function names collide with vafpress function names

### ISSUE THREAD

**Issue by dameer** [vafour/vafpress-framework#21]
I thought it might be good idea to mention that certain functions used in vafpress collide with WP deprecated functions which leads to certain Warnings and Recommendations thrown by ThemeForest-Check plugin...

1) get_links found in the file googlewebfont.php. Deprecated since version 2.1. Use get_bookmarks() instead.

Line 61: $links = $this->get_links();
Line 83: public function get_links()

2) get_theme found in the file codeeditor.php. Deprecated since version 3.4. Use wp_get_theme() instead.

Line 44: 'theme' => $this->get_theme(),
Line 93: public function get_theme() {

Hopefully it helps to make vafpress perfect :)

**Comment by agusmu** [comment]
for reference, my pull request above will solve your issue. please check it. I hope Vafpress team approve it.
