### ISSUE TITLE
vafpress UI styles affect WordPress default styles

### ISSUE THREAD

**Issue by dameer** [vafour/vafpress-framework#23]
I guess you should be able to figure out what's wrong by looking at the image attached much quicker.
Or, if you try to "insert/edit link" in text editor you'll see that something's wrong :)

![ui_issue](https://f.cloud.github.com/assets/1826261/1189753/43386206-2422-11e3-8922-7864bb1ae515.png)

**Comment by agusmu** [comment]
It is because vafpress uses custom jQuery UI theme that "accidentally" override default WordPress jQuery UI theme.

**Comment by ayublin** [comment]
Yup, WP doesn't have jQuery UI styles available for us to use, only partially, so we need to load our own, that's causing styling glitch, as for now we don't have the best solution to prevent it perfectly, but we've just pushed a commit to fix the dialog widget overlay issue.
