### ISSUE TITLE
Dependency and binding fields not loading

### ISSUE THREAD

**Issue by overpink** [vafour/vafpress-framework#24]
Dependency and binding fields not loading when updating to the last commit

**Comment by ayublin** [comment]
Hi Overpink,

Please check out this issue: https://github.com/vafour/vafpress-framework/issues/16

If the issue persist please comment here with the ajax response, thanks!

**Comment by overpink** [comment]
Hello ayublin,

Yeah it was a VP_Security registration issue.. it works now

Thnaks!

**Comment by ayublin** [comment]
You're welcome :)
