### ISSUE TITLE
Slider default example?

### ISSUE THREAD

**Issue by ink888** [vafour/vafpress-framework#28]
Hello there, can I have default slider of your theme option framework?btw, thanks for creating a great wpthemeoption framework... owh..one more..what EOF stand for?

**Comment by ayublin** [comment]
Hi @ello0o,

Please checkout our theme boilerplate repo https://github.com/vafour/vafpress-framework-theme-boilerplate, you will find the code example for almost any features we have.

EOF: End Of File :)

P.S: for non issue question, please go to our [support forum](http://support.vafpress.com).
