### ISSUE TITLE
lot of errors

### ISSUE THREAD

**Issue by partnuz** [vafour/vafpress-framework#29]
I used newest version of vafour with options from boilerplate template and I get following errors

Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'vp_bind_bigcontinents' not found or invalid function name in C:\Program Files\EasyPHP-5.3.6.1\www\wordpress2\wp-content\themes\twentythirteen2\vafpress-framework\classes\control\fieldmulti.php on line 35

Warning: array_merge() [function.array-merge]: Argument #2 is not an array in C:\Program Files\EasyPHP-5.3.6.1\www\wordpress2\wp-content\themes\twentythirteen2\vafpress-framework\classes\control\fieldmulti.php on line 36

Notice: Trying to get property of non-object in C:\Program Files\EasyPHP-5.3.6.1\www\wordpress2\wp-content\themes\twentythirteen2\vafpress-framework\classes\control\fieldmulti.php on line 91

Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'vp_bind_continents' not found or invalid function name in C:\Program Files\EasyPHP-5.3.6.1\www\wordpress2\wp-content\themes\twentythirteen2\vafpress-framework\classes\option\control\set.php on line 250

Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'vp_bind_countries' not found or invalid function name in C:\Program Files\EasyPHP-5.3.6.1\www\wordpress2\wp-content\themes\twentythirteen2\vafpress-framework\classes\option\control\set.php on line 250

**Comment by ayublin** [comment]
Seems like the data sources aren't included, we have included the `data_source.php` that is containing all of the data source functions used, please make sure to include it.
