### ISSUE TITLE
Multiple Select 

### ISSUE THREAD

**Issue by smtir** [vafour/vafpress-framework#3]
This is nice option framework. I did retrieve all of field except multiple. Like i want retrieve multiple select then how i coding that. Can you show me that?

**Comment by ayublin** [comment]
Thanks! If you are using any kind of Multiple Fields which allow to have multiple values (like checkbox, checkimage, sorter), the returned value will be an array of the selected values. And if you want to have access to each value, you can do it with a common PHP practice.

For example, you have an option for social icons set named social_icons_set. And you have selected 3 values, "facebook", "twitter", and "dribbble". If you want to display each value from the set, you can do like this:

```
// retrieve the set (an array returned)
$social_icons = vp_option('social_icons_set');

// access a value using specific index
echo $social_icons[0]; // will print "facebook"
echo $social_icons[1]; // will print "twitter"

// iterate each values
foreach ($social_icons as $social_icon) {
   echo $social_icon;
} 
```

Hope that helps, as this is not an issue, please close it after you got this working :smile:
