### ISSUE TITLE
Metabox: value dependency

### ISSUE THREAD

**Issue by kpodemski** [vafour/vafpress-framework#32]
Hi,

Is there way to create elastic "per value" dependency on metaboxes? For example, I have "Sample group", "Another group". I want to display "Another group" only if "example_field" value from "Sample group" equal to "example_value". Is there a way to do this?

**Comment by ayublin** [comment]
Hi @kpodemski, sorry this isn't currently possible, do you have any use case you can show us? :)

**Comment by kpodemski** [comment]
Hi,

For example we have option called: "Visible in?" and there are checkboxes, I want to show additional metaboxes depends on what user select in "Visible in", for example if user select "Visible in: Public Gallery" we show "Public Gallery" metabox. 

That also concerns selectbox field, If user select some option it's good to display specific metabox, something like "folds" in SMOF or ReduxFramework

**Comment by ayublin** [comment]
I see, Vafpress has dependency feature in metabox, but it's limited to:
1. Field to another field in a metabox
2. Field to another field in a group
3. A field to a group

So the relation won't works across metabox or across group. You can achieve your need in Vafpress by utilizing the dependency feature + group.

So use a checkbox field named `visible_in`, then create several groups based on your options (`group_1`, `group_2`), then each group will depends on `visible_in`, then you just need to supply a function to return true if the `$visible_in === 'group_1'` for the `group_1` and `$visible_in === 'group_2'` for the `group_2`.

You can try out our demo to see how dependency works: http://demo.vafpress.com/vafpress-framework
And the documentation about this: http://vafpress.com/documentation/vafpress-framework/fields-interaction.html
And download the theme boilerplate used in the demo: https://github.com/vafour/vafpress-framework-theme-boilerplate
