### ISSUE TITLE
Metabox Filtering Template support

### ISSUE THREAD

**Issue by cyberwani** [vafour/vafpress-framework#34]
Hi,
Is there any option to show/hide meta fields as per template selected. WPAlachemy have support to add meta-box for particular page-template.

**Comment by daviedR** [comment]
Hi @cyberwani , You can use almost all WPAlchemy options on Vafpress metabox, including 'include_template' and 'exclude_template'. So, yes you can do it as you do on WPAlchemy.

I can see WPAlchemy also has a nice filter named `output_filter`. So if you need more complex logic for showing the metabox, you can use this filter too.

**Comment by cyberwani** [comment]
Currently I am using this. But, when changing template, the fields are not changing as per selected template. Field are affective after updating the entry.

**Comment by daviedR** [comment]
Yes, I think that is the natural behavior of WPAlchemy and we don't make any custom script to handle it on client side. I personally think it is the best that you should update the post first, since it's about post data and WordPress needs to save it indo DB first.

**Comment by cyberwani** [comment]
Thanks @daviedR 
I was hoping something like this, as this type of support is available with Advanced Custom Fields. When you select/change template, then template dependent fields only are visible.
