### ISSUE TITLE
WPEditor Metabox - Insert Media not working?

### ISSUE THREAD

**Issue by ghost** [vafour/vafpress-framework#37]
Not sure if this is a known issue, but I'm unable to insert images or galleries into a WPEditor metabox field. No JS errors, and using the example code that comes with the boilerplate.

**Comment by ayublin** [comment]
Hi @andy-saint, I just tried and it's working fine in my end. What WP version you're on? can you try disabling your plugins and try again?

**Comment by ghost** [comment]
Tested again this morning and it's working, I must of missed something the first time around as it was a very late night :) Thanks anyway for the help :)
