### ISSUE TITLE
Shortcode Content

### ISSUE THREAD

**Issue by joanhard** [vafour/vafpress-framework#38]
How to use shortcode generator for [shortcode] This is a content [/shortcode] ? thanks

**Comment by daviedR** [comment]
Hi joanhard,

Sorry for late response. You can make your shortcode generator to producs "[shortcode] This is a content [/shortcode]" by defining it on the template. Please see this documentation for reference, http://vafpress.com/documentation/vafpress-framework/shortcode-generator/builder.html#template-structure. You have to define the pattern on the `[code]` attribute on each shortcode.
