### ISSUE TITLE
Remove Meta Box

### ISSUE THREAD

**Issue by smtir** [vafour/vafpress-framework#4]
I want to totally remove metabox from option, then what i do if i want to delete?
I just remove code that call metabox , but when i removed it then it will show lot of error.

**Comment by daviedR** [comment]
Hi, can you tell me on what page you saw those errors? Also can you paste the error messages here?

**Comment by ayublin** [comment]
Hi, firstly please advise are you using the newly pushed Vafpress 2.0 or the previous version here https://github.com/vafour/vafpress-framework/tree/v1.2_legacy?

The previous version of Vafpress works by taking all array template files placed under:
https://github.com/vafour/vafpress-framework/tree/v1.2_legacy/vafpress/app/builder/metabox
https://github.com/vafour/vafpress-framework/tree/v1.2_legacy/vafpress/core/builder/metabox
So you can just delete all files under those directories.

But we advise you to use the new version of Vafpress, you can see how to use it on this theme boilerplate:
https://github.com/vafour/vafpress-framework-theme-boilerplate
You can easily remove metaboxes by deleting the metabox objects instantiation in `functions.php` file :smiley:
