### ISSUE TITLE
How can i meta box in page

### ISSUE THREAD

**Issue by imalisiddique** [vafour/vafpress-framework#40]
Hi There,

I want to add meta box in page like post. Is it possible.

**Comment by ayublin** [comment]
Hi,

Yes, please refer to this doc page:
http://vafpress.com/documentation/vafpress-framework/metabox/builder.html

And use the `types` key like this:

`'types' => array('page')`

You can use any other post types for this.

**Comment by imalisiddique** [comment]
thanks @ayublin

**Comment by ayublin** [comment]
You're welcome!
