### ISSUE TITLE
Is it possible to bind 2 field, Both are in different group

### ISSUE THREAD

**Issue by Irfan-Ansari** [vafour/vafpress-framework#41]
Hi,

Is it possible to bind 2 field on in both are in different group. I had tried but no success. Same code working for both field in Same Group But not working in different group.

Here is my Code 

<?php

return array(
        'id'          => 'vp_meta_sample_6',
        'types'       => array('branch'),
        'title'       => __('VP Fixed Group With Item Bindings Fields', 'vp_textdomain'),
        'priority'    => 'high',
        'template'    => array(
                 array(
                        'type'      => 'group',
                        'repeating' => false,
                        'length'    => 1,
                        'name'      => 'binding_groupnew',
                        'title'     => __('New Location', 'vp_textdomain'),
                        'fields'    => array(
                                 array(
                                        'type' => 'select',
                                        'name' => 'big_continent',
                                        'label' => __('Big Continent', 'vp_textdomain'),
                                        'description' => __('Big Continent', 'vp_textdomain'),
                                        'items' => array(
                                                'data' => array(
                                                        array(
                                                                'source' => 'function',
                                                                'value'  => 'vp_bind_bigcontinents',
                                                        ),
                                                ),
                                        ),
                                        'default' => '{{last}}',
                                ),
                                 )

```
            ),
            array(
                    'type'      => 'group',
                    'repeating' => false,
                    'length'    => 2,
                    'name'      => 'binding_group',
                    'title'     => __('Location', 'vp_textdomain'),
                    'fields'    => array(

                            array(
                                    'type' => 'radiobutton',
                                    'name' => 'continent',
                                    'label' => __('Continent', 'vp_textdomain'),
                                    'description' => __('Continent', 'vp_textdomain'),
                                    'items' => array(
                                            'data' => array(
                                                    array(
                                                            'source' => 'binding',
                                                            'field'  => 'big_continent',
                                                            'value'  => 'vp_bind_continents',
                                                    ),
                                            ),
                                    ),
                            ),
                            array(
                                    'type' => 'select',
                                    'name' => 'country',
                                    'label' => __('Country', 'vp_textdomain'),
                                    'description' => __('Country', 'vp_textdomain'),
                                    'items' => array(
                                            'data' => array(
                                                    array(
                                                            'source' => 'binding',
                                                            'field'  => 'continent',
                                                            'value'  => 'vp_bind_countries',
                                                    ),
                                            ),
                                    ),
                            ),
                    ),
            ),
    ),
```

);

/**
- EOF
  */

**Comment by ayublin** [comment]
Discussion moved to support forum: http://support.vafpress.com/topic/is-it-possible-to-bind-2-field-both-are-in-different-group/
