### ISSUE TITLE
Error when saving a Post

### ISSUE THREAD

**Issue by Maj0rrush** [vafour/vafpress-framework#42]
Hi guys,

i use the 

demo.themesmarts.com/euclid/
themesmarts.com/downloads/themes/euclid_theme.zip

Theme with latest Wordpress 3.8.
I get an Error when saving a new Post. 
When i delete the vafpress Folder in Theme Location it works :-(
...............................................................
Warning: strtolower() expects parameter 1 to be string, array given in D:\Apache\xampp\htdocs\wp_rudolphien\wp-includes\formatting.php on line 979

Warning: Cannot modify header information - headers already sent by (output started at D:\Apache\xampp\htdocs\wp_rudolphien\wp-includes\formatting.php:979) in D:\Apache\xampp\htdocs\wp_rudolphien\wp-admin\post.php on line 229

Warning: Cannot modify header information - headers already sent by (output started at D:\Apache\xampp\htdocs\wp_rudolphien\wp-includes\formatting.php:979) in D:\Apache\xampp\htdocs\wp_rudolphien\wp-includes\pluggable.php on line 896
................................................................
I think this Theme uses an old version of vafpress... 
But maybe u can help me with this .. im getting rid of it ...

Thx .. 
Markus

**Comment by ayublin** [comment]
Hi @Maj0rrush,

Sorry but you will need to contact the theme author for the issue, as we're the developer of the framework and the implementation is fully depends on the theme author. We don't have the power to do it. Hope you can understand.

Thanks!

**Comment by Maj0rrush** [comment]
Hey OK Thank you ! i contact the theme developer !
