### ISSUE TITLE
Want New field for  timepicker just like datepicker

### ISSUE THREAD

**Issue by Irfan-Ansari** [vafour/vafpress-framework#43]
Hi, I just want to know how to create my own custom field like date picker.
I did copy paste  datepicker file in class and views but no success.
I want a text field with timepicker available at https://fgelinas.com/code/timepicker/
Can anyone help me to integrate it into vafpress as field name "time"

Thanks
Irfan

**Comment by ayublin** [comment]
Discussion moved to support forum: http://support.vafpress.com/topic/want-new-field-for-timepicker-just-like-datepicker/

P.S: also if you're willing to edit the core, see how kpodemski build his own field: https://github.com/vafour/vafpress-framework/pull/35
