### ISSUE TITLE
Repeating Custom Option Group

### ISSUE THREAD

**Issue by enayet** [vafour/vafpress-framework#44]
Hi,

Can I create repeating custom option group as its available for meta group with add/remove button.  

Say, I want to create a custom group in the option page with a text box, image uploader and url field. And I want user to be able to repeat this option group just by clicking theadd button. 

Is this feature available?

Redux is offering this feature but its still not fully working and bug free.

Thanks,
Sincerely,
-Enayet

**Comment by ayublin** [comment]
Hi @enayet, 

It's not available for now, sorry. But we have long planned to standardize those features to the options panel and even shortcode generator builder. We're close to begin the development of the next major version of Vafpress Framework. As this will be a major version, it will take quite a while before being available for public release.

Thanks!

**Comment by enayet** [comment]
Thanks.

Will eagerly wait for that.

Regards.

**Comment by enayet** [comment]
Hi,

In that case can I use the options in the meta box and show all the meta boxes for a specific page template.

http://www.farinspace.com/page-specific-wordpress-meta-box/

Thanks.

**Comment by ayublin** [comment]
Hi @enayet,

Yup you're right, our metabox class is a modified version of WP Alchemy, please refer to this documentation:
http://www.farinspace.com/wpalchemy-metabox/#filter

You can use those filters to Vafpress Metabox array definition and you should be good to go :)

**Comment by enayet** [comment]
Thanks :)
