### ISSUE TITLE
Do we have place holder?

### ISSUE THREAD

**Issue by enayet** [vafour/vafpress-framework#46]
Hi,

Do we have place holder for textarea, textbox?

Thanks,
Enayet

**Comment by ayublin** [comment]
Hi @enayet,

Currently not, sorry. But this is a good idea and should be easy to implement ! so we probably will implement this soon :)

Thanks!

**Comment by enayet** [comment]
Great :)

**Comment by enayet** [comment]
Hi, If you don't mind would like to suggest two more features:
1. Default button so get the default value loaded. Say for a color field we have a default value, however, if I edit and save then I don't have any option to get the default value again. A link or button would be great to get back the default value again. For now I am providing the default value in the description so that user can at least copy it !
2. Duplicate button for repeating fields (may be beside Remove button), so that user can easily duplicate a group and then edit.

Thanks,
Enayet
