### ISSUE TITLE
text filed value with " problem

### ISSUE THREAD

**Issue by muxahuk** [vafour/vafpress-framework#47]
Hello,
I'm playing around with your framework and found that if i set `textbox` and default value will contain `"` than everithing after firs `"` wount be outputed to the value of input..
The first thing i did was apply esc_attr() on my default value and it helped, but after modefying it with new value with `"` it didn't outputed it needer.
So i found in `view/control/textbox.php` $value; and wraped it with esc_attr() function and now everithing is working fine..
Havent tested it with othere fields, but i think there will be same problem ( may be ).
You could fix these in secconds )
`<input type="text" name="<?php echo $name ?>" class="vp-input input-large" value="<?php echo esc_attr( $value ); ?>" />`

**Comment by ayublin** [comment]
Hi @muxahuk,

You're absolutely right, it's now fixed:
https://github.com/vafour/vafpress-framework/commit/3cdd26ea6e5118a1cfc1048188382a368c06f444

You could have send a pull request also, we would love to accept it :)

Thanks a bunch!
