### ISSUE TITLE
Google font block

### ISSUE THREAD

**Issue by enayet** [vafour/vafpress-framework#48]
Hi,

I saw the vp_font_preview function and some how managed to bind it with other related fields.

An easy ready block should be great with

$preview and $face, $style, $weight, $size, $line_height.

Thanks.

**Comment by ayublin** [comment]
Hi @enayet,

Our philosophy is to make it super flexible for developers to craft their of options using the smallest building block so we prevent to provide ready made option block. But we do understand that it's not for everyone, and typography block seems to be very common so we will definitely consider this. Thanks!

**Comment by enayet** [comment]
Cool :)

**Comment by enayet** [comment]
Hi,

Can we have the drop down to have the charset for google fonts? Is it easy to add using custom data source for latin, cyrillic etc.

Thanks.

Thanks.

**Comment by daviedR** [comment]
Hi Enayet,

We just updated our Google Fonts class 11 days ago. It should be able to get the font's subset now. But we haven't written any documentation about this. If you need to get all available subsets for a specific font, you can use `vp_get_gwf_subset($font_face)` function.

**Comment by enayet** [comment]
Great! Thanks.

**Comment by erbilru** [comment]
Hi

Did you test framework with wordpress 4.0+ ?
i see some errors with font preview.

Thanks
