### ISSUE TITLE
Best way to generate dynamic css with the options

### ISSUE THREAD

**Issue by enayet** [vafour/vafpress-framework#49]
Hi,

What is the best way to generate dynamic css with vafpress, specially for wordpress?

Thanks,
-Enayet

**Comment by ayublin** [comment]
Syamil from Aquagraphite wrote some nice tutorials about this, please check those out:

http://aquagraphite.com/2012/11/using-wp_filesystem-to-generate-dynamic-css/
http://aquagraphite.com/2011/11/dynamically-generate-static-css-files-using-php/

Hope that helps.
