### ISSUE TITLE
Color Picker not closing

### ISSUE THREAD

**Issue by enayet** [vafour/vafpress-framework#50]
Getting this error message:

[screen shot attached]

Timestamp: 1/22/2014 6:43:11 PM
Error: TypeError: this.format is undefined
Source File: http://localhost/TheThemeLab/wordpress-3.8/wp-content/themes/flatone/vafpress-framework/public/js/vendor/bootstrap-colorpicker.js?ver=3.8
Line: 225
![colorpicker](https://f.cloud.github.com/assets/3175292/1973809/e7ec9cfa-8362-11e3-9c61-9a8fe4d390b7.png)

**Comment by enayet** [comment]
Here is the code:

```
            array(
                'type' => 'color',
                'name' => 'primary_color',
                'label' => __('Primary color', 'vp_textdomain'),
                'description' => __('<b>Default:</b> #353B49', 'vp_textdomain'),
                'default' => '#353B49',
                'format' => 'HEX',
            ),              
            array(
                'type' => 'color',
                'name' => 'secondary_color',
                'label' => __('Secondary color', 'vp_textdomain'),
                'description' => __('<b>Default:</b> #EB6D4C', 'vp_textdomain'),
                'default' => '#EB6D4C',
                'format' => 'HEX',
            ),
            array(
                'type' => 'color',
                'name' => 'secondary_color2',
                'label' => __('Secondary color 2', 'vp_textdomain'),
                'description' => __('<b>Default:</b> #6E8697', 'vp_textdomain'),
                'default' => '#6E8697',
                'format' => 'HEX',
            ),  
```

Any idea what I am missing.

Thanks.

**Comment by ayublin** [comment]
Hi @enayet,

Could you please try to change the format string into lowercase? there is a possibility that bootstrap colorpicker doing case sensitive comparison.

**Comment by enayet** [comment]
Great! Excellent! Thanks.

Relieved :)

Please update the documentation here:

http://vafpress.com/documentation/vafpress-framework/controls/fields.html 

format (optional): HEX, RGB, or RGBA, default to HEX

with lowercase :)

:+1: 

Regards.
