### ISSUE TITLE
How to entry double quote ( " " )  in the textbox?

### ISSUE THREAD

**Issue by enayet** [vafour/vafpress-framework#51]
Its only accepting single quote.

Reason:

Say, I want to create a textbox for Contact form 7 short code which by default generates shortcode with douple code like:

[contact-form-7 id="11" title="Contact form 1"]

Many thanks for your support.

Regards.

**Comment by enayet** [comment]
In Meta box.

Thanks.

**Comment by ayublin** [comment]
Hi, could you elaborate more? in what case the textbox doesn't accept single quote?

**Comment by enayet** [comment]
Yes, its accepting single quote but not double quote in textbox in meta.

**Comment by ayublin** [comment]
Ahh yeah I meant double quote, I tried inputting a double quote and it's saved properly.

**Comment by enayet** [comment]
Not sure, at my end its not working. I will check.

If couldn't get the issue (along with some other minor issues) will provide you the link with access when I upload online.

I really appreciate your help and support.

Thank you so much.

Regards,
Enayet

**Comment by enayet** [comment]
Hi,

I moved the option from meta to option panel still the double quote not working.

When I first entry and save its got saved and working fine. I can get the value in the front end.

![theme options flatone 9877 wordpress](https://f.cloud.github.com/assets/3175292/2001172/5ccc6526-8590-11e3-8087-12aac78b616e.png)

Even if I refresh the page its there.

However if I click Theme Options from Appearance menu its cut off.

![theme options flatone 9877 wordpress1](https://f.cloud.github.com/assets/3175292/2001173/60e647a8-8590-11e3-9464-8132c3cde091.png)

Thanks.

**Comment by ayublin** [comment]
Hi @enayet,

Can you please make sure you use the very latest version of Vafpress? I remember fixed that kind of issue in the latest commit.

**Comment by enayet** [comment]
Hi,

I think I last downloaded early January.

Will get the latest one again.

Thanks.

**Comment by ayublin** [comment]
Alright, feel free to re-open if the issue persists with the latest version :)
