### ISSUE TITLE
Upload field size option

### ISSUE THREAD

**Issue by enayet** [vafour/vafpress-framework#52]
Hi,

The upload field returns the direct path of the image.

As the upload is using the wp default media upload, is there any way we can use the "Size" field value of "Attachment Display Settings"?

As you know themeforest doesn't allow to use timthumb!

Thanks.

**Comment by ayublin** [comment]
Sorry that's not possible right now, we're using something like this as the workaround:

```
global $wpdb;
$query = "SELECT ID FROM {$wpdb->posts} WHERE guid = '$your_image_url'";
$id = $wpdb->get_var($query);
wp_get_attachment_image($id, 'featured-' . $your_desired_size_name);
```

**Comment by enayet** [comment]
Thanks :)

I think this is for meta.

How it will work for the options?

https://github.com/syamilmj/Aqua-Resizer

Can we use it for theme forest theme?

Many thanks.
