### ISSUE TITLE
CSS not loading on toggle [metabox]

### ISSUE THREAD

**Issue by iqbalbary** [vafour/vafpress-framework#55]
In my case, css is not loading on Toggle. Also i see in your demo setting section - Input & checkbox field UI is looking grate but in metabox section(within post), its showing the default of browser. So, is that an issue or you coded like that way?

**Comment by enayet** [comment]
Hi, I had this similar issue. I think this is default, as the online demo is also showing this.

Thanks.

**Comment by daviedR** [comment]
Hi guys, we don't experience this issue. Can you check if the vp-metabox.css is loaded in the page?

**Comment by enayet** [comment]
![http---demo vafpress com- -vafpress-framework](https://f.cloud.github.com/assets/3175292/2239715/3c00b276-9c4b-11e3-9def-914981563159.png)

Hi, The screen shot is taken from the live demo of vafpress.

Thanks.

**Comment by daviedR** [comment]
Owww :) Sorry I thought there was an error or something buggy on the styles. About that toggle field itself, we don't have specific style for it. So it looks as a default checkbox field.

We separate the Options Page's CSS, Metabox's CSS, and Shortcode Generator's CSS. We wish to merge it into one CSS at the next update, so every vafpress components will looks the same everywhere.

Thanks

**Comment by enayet** [comment]
Thank you :)

**Comment by iqbalbary** [comment]
Thanks!

**Comment by thednp** [comment]
Thanks :)
