### ISSUE TITLE
speed

### ISSUE THREAD

**Issue by szepeviktor** [vafour/vafpress-framework#60]
Good morning!
I'd like to use VAF in handmade websites, that means I put in every line of js and css by hand. So it is not needed to output css.
Is VAF running on the frontend also?
How is it possible to limit (parsing and execution of) VAF to
1. the backend
2. a specific page (the theme settings page) of the backend?

**Comment by thednp** [comment]
Vafpress runs in front-end as to provide options and metabox values. About limit I am not sure what you mean.

**Comment by szepeviktor** [comment]
I mean that - as I think - a large part of the code is neccessary for the backend. In case of metaboxes - as I think - a large part of the class/code is not neccessary to display the frontend.

I am looking for an option panel that runs (or parses=require('backend-class.php')) no backend code on the frontend.

**Comment by szepeviktor** [comment]
Simply: an option panel that has a small _separate_ part for the frontend.

**Comment by thednp** [comment]
Basically you can have as many panels as you wish. As far as I know there panels or metaboxes only  generate values into the database, has nothing to do with front-end coding. The front-end coding only access those values.

**Comment by szepeviktor** [comment]
Thank you!
I'd like to avoid parsing a lot of PHP code. I know it does not generate frontend HTML code, and it does not even run, but the PHP parser must go through all admin classes, read the .php files and compile them.
Do you have any suggestion like

``` PHP
if (is_admin()) {
    require('admin-classes.........');
}
```

**Comment by ayublin** [comment]
Hi @szepeviktor, @thednp is right, we don't parse or do heavy back end process in the front end, you shouldn't worry about this as we implement class auto loading and etc. Maybe it's may lack of knowledge, but I don't know if .php files needed to be compiled since it's interpreted language.

**Comment by szepeviktor** [comment]
AFAIK when you write `function b {do_this();}` it is parsed and compiled to byte code (e.g. what APC caches), but if you write `if (is_admin()) {require('class.php')}` class.php is not even read from the disk.
