### ISSUE TITLE
Site down?

### ISSUE THREAD

**Issue by dy2288** [vafour/vafpress-framework#71]
Hey! Was relying on your documentation here:
http://vafpress.com/documentation/vafpress-framework/

However I see your site is currently down. Will it be restored soon?

**Comment by ayublin** [comment]
I can see it's up, and tested here too:
http://www.downforeveryoneorjustme.com/http://vafpress.com/

Can you check again?

**Comment by dy2288** [comment]
Thanks, issues with my DNS. Got me worried for a moment (I probably should have checked first using that site though). Cheers.
