### ISSUE TITLE
ordering posts based on metabox value

### ISSUE THREAD

**Issue by vivevio** [vafour/vafpress-framework#84]
hello,

same as the title, how to ordering posts based on metabox value?
I try to using WP_Query like this

```
$args = array(
                    'post_type'         => 'product',
                    'posts_per_page'    => get_option('posts_per_page'),
                    'paged'             => $paged,
                    'order'             => 'DESC',
                    'orderby'           => 'meta_value',
                    'meta_key'          => 'price'
                 );
```

but its not work.

thanks.

**Comment by scrobbleme** [comment]
This is not the support forum: http://support.vafpress.com/
Have you read the manual? http://vafpress.com/documentation/vafpress-framework/metabox/retrieving-value.html

Okay, the website seems to be currently down. So try this one: http://webcache.googleusercontent.com/search?q=cache:WHPM-axEIzYJ:vafpress.com/documentation/vafpress-framework/metabox/retrieving-value.html+&cd=1&hl=de&ct=clnk&gl=de

**Comment by richardlin** [comment]
thanks @scrobbleme for answering...

not sure what happened but our website is up now. :)
please check the manual @webfreaks

**Comment by vivevio** [comment]
upz, so im in the wrong place @scrobbleme. my fault.
ok thank for the answer guys.
