### ISSUE TITLE
Textarea adds backslashes after saving

### ISSUE THREAD

**Issue by grafixes** [vafour/vafpress-framework#9]
Hi,

I'm saving HTML into the textarea. For example the input looks like:

<pre><code>&lt;ul class="unordered-list"&gt;
    &lt;li>list item&lt;/li&gt;
    &lt;li>list item&lt;/li&gt;
&lt;/ul&gt;</code></pre>

But e.g. after saving the theme options it adds a backslashes to the class="" like so:

<pre><code>&lt;ul class=\\\\\\\"unordered-list\\\\\\\"&gt;
    &lt;li>list item&lt;/li&gt;
    &lt;li>list item&lt;/li&gt;
&lt;/ul&gt;</code></pre>

And they keep adding.

I read that this could be solved be adding stripslashes() around the output. How can I fix this?

Max

**Comment by ayublin** [comment]
Hi Max,

where is this happening? metabox or options?

Thanks.

**Comment by grafixes** [comment]
Hi,

On the options (theme options).

**Comment by ayublin** [comment]
Thanks for the report Max, you're right, we forgot to deal with slashes added by WordPress via `add_magic_quotes` function to $_POST, $_GET, $_REQUEST, and $_COOKIE data, we're going to fix this soon and notify you.

**Comment by grafixes** [comment]
Nice, thanks! I'm looking forward to the update.

**Comment by ayublin** [comment]
Hi Max, issues with slashes should be fixed now, if you found that the problem still persist feel free to re-open the issue. Thanks!
